name: mpac_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  dartz: ^0.10.1
  dio: ^5.1.0
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.20
  flutter_bloc: ^7.3.3
  get_it: ^7.2.0
  bloc:
  json_annotation:
  built_value: ^8.4.4
  another_flushbar: ^1.12.29
  flutter_launcher_icons: ^0.12.0
  meta: ^1.8.0
  sizer: ^2.0.15
  flutter_svg: ^1.1.5
  animations: ^2.0.7
  firebase_core: ^2.8.0
  firebase_dynamic_links: ^5.3.2
  injectable: ^2.1.1
  pin_code_fields: ^7.4.0
  intl_phone_number_input: ^0.7.2
  phone_number: ^1.0.0
  country_code_picker: ^3.0.0
  image_picker: ^0.8.7+1
  persistent_bottom_nav_bar: ^5.0.2
  photo_manager: ^2.6.0
  flutter_reaction_button: ^2.0.1+2
  google_sign_in: ^6.0.2
  flutter_datetime_picker: ^1.5.1
  dash_chat: ^1.1.16
#  sendbird_sdk: ^3.2.13
  sendbird_chat_sdk: ^4.0.0
  scrollable_positioned_list: ^0.3.8
  easy_image_viewer: ^1.2.0
  string_validator: ^1.0.0
  universal_io: ^2.2.0
  audioplayers: ^3.0.1
  path_provider: ^2.0.14
  image_cropper: ^3.0.2
  dotted_border: ^2.0.0+3
  firebase_messaging: ^14.3.0
  flutter_local_notifications: ^13.0.0
  permission_handler: ^10.2.0
  video_player: ^2.7.0
  mime: ^1.0.4
  device_info_plus: ^8.1.0
  chewie:
  pod_player: ^0.1.5
  inview_notifier_list: ^3.0.0
  video_compress: ^3.1.2
  shimmer: ^3.0.0
  wechat_assets_picker: ^8.4.1
  stacked_firebase_auth: ^2.19.2
  file_picker: ^5.2.6
  iconify_flutter: ^0.0.5
  visibility_detector: ^0.4.0+2
  preload_page_view: ^0.1.6
  google_fonts: ^3.0.1
  lottie: ^1.4.2


  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_dotenv: ^5.0.2

dev_dependencies:
  auto_route_generator: ^6.0.2
  build_runner: ^2.3.3
  built_value_generator: ^8.4.4
  flutter_test:
    sdk: flutter
  injectable_generator:
  json_serializable:
  flutter_lints: ^2.0.1

dependency_overrides:
  universal_html: 2.2.3
  meta: 1.9.1
  collection: 1.17.1
  async: 2.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logos/launcher.png"
  adaptive_icon_background: "assets/images/logos/launcher_background.png"
  adaptive_icon_foreground: "assets/images/logos/launcher.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/icons/
    - assets/images/logos/
    - assets/images/general/
    - assets/images/nav/
    - assets/images/nav/active/
    - assets/images/nav/inactive/
    - assets/images/account_icons/
    - assets/images/sports/
    - assets/images/reactions/
    - assets/sounds/
    - assets/images/sub_sports/
    - assets/images/sports_new/
    - assets/fonts/
    - assets/jsons/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
